myapp/urls.py
from django.urls import path, include
from myapp import views
urlpatterns = [
 path('', views.index, name='index'),
 path('contacto', views.contacto, name='contacto'),
 path('app_forecast', views.app_forecast, name='app_forecast'),
 path('app_irradiance_summer_winter', views.app_irradiance_summer_winter, name='app_irradiance_summer_winter'),
 path('app_sun_position', views.app_sun_position, name='app_sun_position'),
 path('ckeditor/', include('ckeditor_uploader.urls')),
 ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('myapp/', include('myapp.urls')),
    path('admin/', admin.site.urls),
    path('consulta/', include('consulta.urls')),
    path('papers/', include('papers.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

papers/urls.py
from django.urls import path


from papers.views import Index, Paper, BuscarPaper, BuscarPaper2, index

urlpatterns = [
    #path('', index, name='index'),
    path('', Index.as_view(), name='papers'),
    path('papers/<slug:slug>/', Paper.as_view(), name='paper'),
    path('buscar_paper/', BuscarPaper.as_view(), name='buscar_paper'),
    path('buscar_paper2/', BuscarPaper2.as_view(), name='buscar_paper2'),
    ]

papers/models.py
from django.db import models

# Create your models here.

from ckeditor_uploader.fields import RichTextUploadingField

class Papers(models.Model):

    fecha = models.DateField(blank=True, null=True)
    contenido = RichTextUploadingField('contenido')
    slug = models.CharField(max_length=128, unique=True, default='---')
    ruta_imagen = models.FileField(upload_to='videos/%Y/%m/%d', blank=True, null=True)
    titulo = models.CharField(max_length=200, default='---')
    resumen = models.CharField(max_length=200, default='---')

papers/forms.py
from django.forms import ModelForm
from .models import Papers
from django import forms

class SearchPaperForm(forms.Form):
    querycom = forms.CharField(label='Please, enter article title',
    widget=forms.TextInput(attrs={'size': 32, 'class':'form-control'}))

papers/views.py
from django.shortcuts import render

# Create your views here.

from papers.models import Papers
from django.views.generic import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from papers.forms import SearchPaperForm
import json
from django.http import HttpResponse

from django.shortcuts import render
from django.template import RequestContext, loader
from django.shortcuts import redirect
from django.http import Http404
from django.shortcuts import render_to_response
from django.template import RequestContext




class BuscarPaper(View):
    def get(self, request):
        if request.is_ajax:
            palabra = request.GET.get('term', '')
            print(palabra)
            paper = Papers.objects.filter(titulo__icontains=palabra)
            results = []
            for an in paper:
                data = {}
                data['label'] = an.titulo
                results.append(data)
            data_json = json.dumps(results)
        else:
            data_json = "fallo"
        mimetype = "application/json"
        return HttpResponse(data_json, mimetype)


class BuscarPaper2(View):
    def get(self, request):
        if request.is_ajax:
            q = request.GET['valor']
            paper = Papers.objects.filter(titulo__icontains=q)
            results = []
            for rec in paper:
                print(rec.titulo)
                #print(rec.fecha)
                print(rec.ruta_imagen)

                data = {}
                data['titulo'] = rec.titulo
                
                data['contenido'] = str(rec.contenido)
                results.append(data)
            data_json = json.dumps(results)

        else:
            data_json = "fallo"
        mimetype = "application/json"
        return HttpResponse(data_json, mimetype)



def index(request):
    params = {}
    search = SearchPaperForm()
    params['search'] = search
    return render(request, 'papers/index.html', params)


class Index(View):
    model = Papers
    template = 'papers/index.html'

    def get(self, request):

        params = {}
        papers = Papers.objects.all().order_by('fecha')

        paginator = Paginator(papers, 3)
        page = request.GET.get('page')
        try:
            papers1 = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            papers1 = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            papers1 = paginator.page(paginator.num_pages)
        params['papers1'] = papers1
        search = SearchPaperForm()
        params['search'] = search
        return render(request, self.template, params)



class Paper(View):
    template = 'papers/paper.html'

    def get(self, request, slug):

        params = {}
        paper = Papers.objects.get(slug=slug)
        params['paper'] = paper

        return render(request, self.template, params)

templates/papers/index.html
{% extends "plantilla.html" %}

{% load static %}
{% load i18n %}


{% block content%}







    <div class="container" style="margin-left:140px; padding: 0px 10px;">
        <div class="jumbotron">
        <h1>PVSIM Fact Sheets</h1>
        </div>
    </div>
    <main class="container" style="margin-left:140px; padding: 0px 10px;">
        <div class="row" >
         <section id="todos_los_productos" class ="row" >
			
			<hr/>
			<div id="contenedor_filtros" class="row" style="margin-left:10px; padding: 0px 10px;">
				<div id="filtros_productos" class="col-xs-12">
					<form id="searchr-form" action="" method="post" >{% csrf_token %}
						<div class="campo_busqueda col-xs-12 " >
						{{ search }}
						<input type="button" id="boton_prod" value="View Article"/>
						</div>
					</form>
				</div>
			</div>
			
			</section>
			<div id="contenedor_filtrado" class="container">
			</div>
        </div>

	</main>
 

  
  <!-- ########################################
  #########3PAGINATOR ##############3
  ###################################################-->
<div class="container" style="margin-left:140px;">
				<div class="row justify-content-center"  style="background-color:#fff; z-index:20;" "margin-left:140px;">
					<div class =" col-12 pt-3" style="background-color:#fff; "  >
							<span class="step-links">
								{% if papers1.has_previous %}
									<a href="?page={{ papers1.previous_page_number }}">Previus</a>
								{% endif %}

								<span class="current">
									Page {{papers1.number }} de {{ papers1.paginator.num_pages }}.
								</span>

								{% if papers1.has_next %}
									<a href="?page={{ papers1.next_page_number }}">Next</a>
								{% endif %}
							</span>
                        <hr/>
					</div>
				</div>
</div>
<div id="papers_index" class="container" style="margin-left:140px;">


     {% for papers in papers1  %}
    <div class="row justify-content-center align-items-center border  my-3 " style=" z-index:20;" "margin-left:10px;">
        <div class="col-12 py-3" style="background-color:#fff; ">
            <div class="row   ">
                <div id="papers_contenido" class="col-12 py-3 ">
                    <h4>"{{papers.titulo}}".</h4>
                    {{papers.contenido|safe|slice:":455"}}
                </div>
                <div class="col-12  py-3">
                    <div class="row justify-content-between">
                        <div class="col-6 col-sm-4 ">
                             <a href="{% url 'paper' slug=papers.slug   %} " target="_blank">Read Article</a>
                        </div>
                        <div class="col-6 col-sm-4">
                            <a href="{% url 'contacto' %}" target="_blank">Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 
     </div>

     {% endfor %}
 </div> 


{% endblock %}


{% block scripts %}
 <script src="{% static 'js/jquery-ui.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
<script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>

	<script type="text/javascript">
		$( "#id_querycom" ).autocomplete({
		source:"/papers/buscar_paper/"
		});
	</script>




{% endblock %}

templates/papers/paper.html
{% extends "myapp/plantilla.html" %}

{% load static %}
{% load i18n %}
{% block cabeceranoticia %}
    <div class="col-12" style="position:absolute; top:0px; z-index:0;margin-left:140px;"> 
      <!--<img id="imagen_inicio" src="/media/presentacion/cabecera_menu.jpeg" style="width:100%; " />-->
    </div>
{% endblock %}

{% block content %}





 <section class="container-fluid " style="margin-left:140px;">
    <div class="row">
        <div class="col-12 " style="padding:50px;  ">

        </div>
    </div>
</section>
 

 <!--------------------------------------------------------
  ---------------VIDEO ---------------------------------
  --------------------------------------------------------->
<div id="noticias_index_p" class="container" style="margin-left:140px;">
    <div class="row justify-content-center align-items-center   " >
        <div class="col-12" style=" top:0px; z-index:0; "> 
          <!--<img id="imagen_inicio" src="/media/presentacion/cabecera_menu.jpeg" style="width:100%; " />-->
        </div>
    </div>

    <div class="row justify-content-center align-items-center mb-2 px-3" >
        <div class="col-12 py-3" style="background-color:#fff; ">
            <div class="row   ">
                <div id="papers_contenido" class="col-12 py-3 ">
                    <h4>"{{paper.titulo}}".</h4>
                    {{paper.contenido|safe}}
                </div>
                <div class="col-12  py-3">
                    <div class="row justify-content-between">
                        <div class="col-6 col-sm-4 ">
                              
                        </div>
                        <div class="col-6 col-sm-4">
                            <a href="{% url 'contacto' %}" target="_blank">Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>
 </div>

 


 
<section class="container"style="margin-left:140px;">
    <div class="row">
        <div class="col-12" style="padding:80px;  ">
           <br/> 
        </div>
    </div>
</section>

 
{% endblock %}
{% block javascript %}
    <script src="http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>
    <script type="text/javascript" src="{% static 'js/juan_ajax.js' %} " ></script>





    <!--------------------------------------------------------------------------------------------------------
    --------- AUTOCOMPLETAR
    --------------------------------------------------------------------------------------------------------->
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>

    <script>
    $( "#autocomplete" ).autocomplete({
        source:"../../predica_pastor/"
    });
    </script>


{% endblock %}